# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20170722_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('JAVASCRIPT', 'javascript'), ('JAVA', 'java'), ('PYTHON', 'python'), ('XML', 'xml'), ('RUBY', 'ruby'), ('SASS', 'sass'), ('MARKDOWN', 'markdown'), ('MYSQL', 'mysql'), ('JSON', 'json'), ('HTML', 'html'), ('HANDLEBARS', 'handlebars'), ('GOLANG', 'golang'), ('CSHARP', 'csharp'), ('ELIXIR', 'elixir'), ('TYPESCRIPT', 'typescript'), ('CSS', 'css')], default='JAVA', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='theme',
            field=models.CharField(choices=[('MONOKAI', 'monokai'), ('GITHUB', 'github'), ('TOMORROW', 'tomorrow'), ('KUROIR', 'kuroir'), ('TWILIGHT', 'twilight'), ('XCODE', 'xcode'), ('TEXTMATE', 'textmate'), ('SOLARIZED_DARK', 'solarized_dark'), ('SOLARIZED_LIGHT', 'solarized_light'), ('TERMINAL', 'terminal')], default='GITHUB', max_length=100),
        ),
    ]
