# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20170722_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('handlebars', 'handlebars'), ('typescript', 'typescript'), ('ruby', 'ruby'), ('javascript', 'javascript'), ('python', 'python'), ('markdown', 'markdown'), ('mysql', 'mysql'), ('golang', 'golang'), ('java', 'java'), ('csharp', 'csharp'), ('xml', 'xml'), ('json', 'json'), ('elixir', 'elixir'), ('sass', 'sass'), ('html', 'html'), ('css', 'css')], default='java', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='theme',
            field=models.CharField(choices=[('monokai', 'monokai'), ('github', 'github'), ('tomorrow', 'tomorrow'), ('kuroir', 'kuroir'), ('twilight', 'twilight'), ('xcode', 'xcode'), ('textmate', 'textmate'), ('solarized_dark', 'solarized_dark'), ('solarized_light', 'solarized_light'), ('terminal', 'terminal')], default='github', max_length=100),
        ),
    ]
