# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20170722_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('typescript', 'typescript'), ('xml', 'xml'), ('json', 'json'), ('python', 'python'), ('java', 'java'), ('javascript', 'javascript'), ('markdown', 'markdown'), ('ruby', 'ruby'), ('handlebars', 'handlebars'), ('mysql', 'mysql'), ('golang', 'golang'), ('csharp', 'csharp'), ('css', 'css'), ('sass', 'sass'), ('html', 'html'), ('elixir', 'elixir')], default='java', max_length=100),
        ),
    ]
