# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20170805_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('css', 'css'), ('html', 'html'), ('json', 'json'), ('handlebars', 'handlebars'), ('golang', 'golang'), ('python', 'python'), ('java', 'java'), ('ruby', 'ruby'), ('markdown', 'markdown'), ('sass', 'sass'), ('mysql', 'mysql'), ('csharp', 'csharp'), ('typescript', 'typescript'), ('elixir', 'elixir'), ('xml', 'xml'), ('javascript', 'javascript')], default='java', max_length=100),
        ),
    ]
